[package]
name = "pckr"
version = "0.1.0"
edition = "2024"

[dependencies]
home = "0.5"
inquire = { version = "0.7.5" }
dirs = "6.0.0"
toml = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.98"
log = "0.4.27"
regex = "1.11.1"
walkdir = "2"
